image: docker:19

services:
  - docker:dind

stages:
  - build_prod
  - check_port_prod
  - deploy_prod

variables:
  IMAGE_NAME: my-oee-app
  CONTAINER_NAME: my-oee-app
  HOST_PORT: 8080
  INSIDE_PORT : 8080
  ENV_FILE: .env.production  # Define the environment file

before_script:
  - echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
  - echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
  - source ~/.bashrc  # For Bash
  - |
    if [ -s "$NVM_DIR/nvm.sh" ]; then
      \. "$NVM_DIR/nvm.sh"  # Load NVM
    fi
  - nvm install 18.17.1
  - nvm use 18.17.1
  - node --version
  - npm --version

build_prod:
  stage: build_prod
  image: node:18
  tags:
    - oee_apps_prod
  when: manual
  script:
    - echo "VUE_APP_URL_BACKEND=$CI_VUE_APP_URL_BACKEND" >> $ENV_FILE
    - echo "VUE_APP_SERVICE_AUTH_PASSWORD=$CI_SERVICE_AUTH_PASSWORD" >> $ENV_FILE
    - echo "VUE_APP_SERVICE_AUTH_USER=$CI_SERVICE_AUTH_USER" >> $ENV_FILE
    - echo "VUE_APP_SECRET_FRONT=$CI_VUE_APP_SECRET_FRONT" >> $ENV_FILE
    - echo "PATH='${PATH}'"
    - npm install --force
    - npm run build
  artifacts:
    paths:
      - dist/
      - $ENV_FILE

check_port_prod:
  stage: check_port_prod
  tags:
    - oee_apps_prod
  needs:
    - build_prod
  script:
    - |
      PORT=8080
      CONTAINER_ID=$(docker ps -qf "expose=$PORT")
      if [ -n "$CONTAINER_ID" ]; then
        echo "Container is already running on port $PORT. Stopping and removing it..."
        docker stop $CONTAINER_ID
        docker rm $CONTAINER_ID
      else
        echo "No container is running on port $PORT."
      fi

deploy_to_prod:
  stage: deploy_prod
  script:
    - echo "Deploying to prod server with PM2"
  tags:
    - oee_apps_prod
  needs:
    - build_prod
    - check_port_prod
  script:
    - echo "Stopping PM2 process if it exists"
    - pm2 delete oee_app || echo "No PM2 process to stop"

    # Copy dist folder to the production server if needed (e.g., SCP or rsync)
    - echo "Copying dist folder to server (optional, depending on your setup)"
    - scp -r dist/* ubuntu@ip-172-31-33-57:/home/ubuntu/oee_app

    # Start the app using PM2
    - echo "Starting Vue app with PM2"
    - pm2 start /home/ubuntu/oee_app --name "oee_app" -- -p 8080 -c-1 ./dist

    # Optionally save the PM2 process list to auto-start on boot
    - pm2 save
  # only:
  #   - main  # Deploy only from the 'main' branch (you can modify this based on your needs)
  when: manual  # Make it manual if you want to control when deployments happen
