image: node:18  # Use a Node.js Docker image for the CI/CD pipeline

stages:
  - build_prod
  - deploy_prod

variables:
  ENV_FILE: .env.production  # Define the environment file
  VUE_APP_PATH: /home/ubuntu/oee_app  # Define your Vue.js app's path on the server

before_script:
  - echo "Installing NVM"
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash  # Install NVM
  - source ~/.nvm/nvm.sh
  - nvm install 18.17.1
  - nvm use 18.17.1
  - node --version
  - npm --version

build_prod:
  stage: build_prod
  script:
    - npm install  # Install dependencies
    - npm run build  # Build the production app

deploy_prod:
  stage: deploy_prod
  script:
    - echo "Deploying Vue.js app to the server"
    - cd $VUE_APP_PATH  # Navigate to your app directory
    - git pull origin main  # Optional: Update app from Git (if using Git for deployment)
    - npm install --production  # Install production dependencies
    - pm2 stop oee-app || true  # Stop the app if it's running
    - pm2 start npm --name "oee-app" -- run start  # Start the app using PM2
    - pm2 save  # Save PM2 process list for automatic startup
